apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akhq.fullname" . }}
  labels:
    {{- include "akhq.labels" . | nindent 4 }}
data:
  application.yml: |
    {{- .Values.configuration | toYaml | nindent 4 }}
