replicaCount: 1

image:
  repository: tchiotludo/akhq
  tag: 0.25.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

configuration: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
